package com.example.habittracker

/**
 * Data class representing a Habit entity.
 * 
 * @property id The unique identifier generated by Firestore.
 * @property name The name of the habit.
 * @property notes Additional details or reminders about the habit.
 * @property completed Whether the habit is currently completed for the day.
 * @property completionHistory A list of dates when this habit was completed (stored as "yyyy-MM-dd").
 * @property totalCompletions The total number of times this habit has been completed.
 * @property frequency The frequency type (Daily, Weekly, Monthly).
 * @property selectedDays List of days (e.g., "Mon", "Tue") for Daily frequency.
 * @property reminderTime The time for the habit (e.g., "08:00 AM").
 */
data class Habit(
    val id: String = "",
    val name: String = "",
    val notes: String = "",
    var completed: Boolean = false,
    val completionHistory: List<String> = emptyList(),
    val totalCompletions: Int = 0,
    val frequency: String = "Daily",
    val selectedDays: List<String> = emptyList(),
    val reminderTime: String = ""
)
